### ISSUE TITLE
Crash on changing level

### ISSUE THREAD

**Issue by EugeneLesnov** [NickMcConnell/FAangband#266]
Here's the message I got if run with x11 frontend:
```faangband: gen-cave.c:2806: town_gen: Assertion `i < world->num_towns' failed.```

When I run the game with curses:
![изображение](https://user-images.githubusercontent.com/53460983/132135169-fd70c8fa-6f47-4e2c-bd9b-6af01d0c4c19.png)

My save file. Just go upstairs and you'll get a crash.
[Eugene.tar.gz](https://github.com/NickMcConnell/FAangband/files/7112034/Eugene.tar.gz)

This is compiled version from main branch with latest changes. My OS is Kubuntu 21.04.

I don't know whether it's important, but I played with curses and sdl2-mixer enabled in terminal before crash occurred.

**Comment by NickMcConnell** [comment]
OK, this is a bug - upstairs aren't handled properly in the hybrid dungeon.  Thanks for the excellent report.
