### ISSUE TITLE
Hybrid dungeon upstairs bug

### ISSUE THREAD

**Issue by EugeneLesnov** [NickMcConnell/FAangband#269]
In hybrid dungeon mode when player reaches Nan Dungortheb upstairs are not generated. When diving deeper (starting from Nargothrond 55) player basically finds himself on `Pile of passable rubble`.

I tried to edit world.txt (In hybrid dungeon there missing north connections in Nan Dungorthreb) but this didn't solve the problem.
So, no PR, just an issue..

**Comment by NickMcConnell** [comment]
This is intentional 😄

**Comment by EugeneLesnov** [comment]
Oh my :D I spent few hours debugging this haha
Awkward moment
