### ISSUE TITLE
Baphomet the Minotaur Lord

### ISSUE THREAD

**Issue by eugenelesnov** [NickMcConnell/FAangband#282]
With this issue, I propose to replace Baphomet the Minotaur Lord with another unique monster. Just to make the monsters even more in line with the spirit of the First Age of Middle-earth.

I will try to look for suitable replacement options (Looking forward to diving into the Silmarillion!)

**Comment by EugeneLesnov** [comment]
Well, first candidat is **_Salgant_**:

> Salgant was the chief of the House of the Harp, who bore the emblem of a golden harp upon a sable field. Unlike his brave folk, he was a craven that "fawned upon Meglin". He was said to be heavy and squat, being the only one of the Gondothlim to ride at battle.
> 
> When Melko's armies approached the city, he and Meglin alone convinced King Turgon to hold the city and guard the treasures, and though Meglin spoke he backed him up. In the beginning of the Fall of Gondolin, Meglin's plan was to attack Tuor's house, and ordered Salgant to delay Tuor and his folk of the Wing and take them into the deadliest of the battle. However, Salgant became frightened, rode home and "lay... aquake on his bed".
> 
> As the battle went worse, Turgon ordered him to the Great Market to reinforce Glorfindel and the house of the Golden Flower. But in his treachery he concealed this to his folk, saying they had to garrison the Lesser Market, where he lived. There his men fretted, abandoning Salgant, and with their deeds in battle they could redeem the cowardice of their lord.
> 
> It is suggested that he either perished by fire upon his bed or became a buffoon of Melko.

**Comment by NickMcConnell** [comment]
There are many traditional (D&D, Angband, whatever) monster still in FA which I have no plans to remove.  My policy is to remove Tolkien monsters which are not First Age, and other monsters which are clearly from other mythologies.  I'm happy, though, to still allow Feagwath, Vecna, and so on - and Baphomet falls into this class.
