### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/FAangband#314]
[Glang.zip](https://github.com/NickMcConnell/FAangband/files/7748520/Glang.zip)
When I try to go up with less than symbol key game crashes to desktop with no error message. Windows 11 PC.

**Comment by NickMcConnell** [comment]
I haven't been able to repeat this, or find anything wrong in the current development version.  If you're playing 2.0.1, trying the latest development version from the release page might help.  There have been a number of bugs fixed since 2.0.1 was released (I really should release 2.0.2).

**Comment by davidk64fnq** [comment]
Thanks for that - yes 2.0.1 fixes it - I was playing 2.0.0
