### ISSUE TITLE
Weasel tile attempt

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/FAangband#317]
![Maddened Weasel](https://user-images.githubusercontent.com/63939880/147017082-a1244b08-113c-40d8-b08a-5ba53712d005.png)
So before adding it to the tile sheet and raising a pull request what is the process for getting approval for the tile? Are there any guidelines for where on the sheet it gets put or is it just a case of pick a spare spot near tiles of similar ilk? Are the vanilla and FAangband tile sheets kept coordinated or do they evolve independently. I believe there is very little work done on the vanilla Gervais tile sheet?

**Comment by NickMcConnell** [comment]
I believe the V and FA Gervais tile sets are the same.  If you want to do any work on the FA one feel free to do what you judge best; we can deal with the unlikely event that I see anything that needs changing if that happens.

**Comment by davidk64fnq** [comment]
Okay I'll try adding the weasel to the FAangband sheet only. If somebody happens along and does a nicer weasel they can soon replace this one!

**Comment by NickMcConnell** [comment]
Done in e7aae8d7d
