### ISSUE TITLE
Scroll of magic mapping & displaying road tiles

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/FAangband#325]
I read a scroll of magic mapping  and it revealed all tiles except roads which were black spaces.

Is this intended?

**Comment by davidk64fnq** [comment]
This time it's as if a random number of tiles have been displayed as the black spaces are a mixture of terrain when I encounter them post reading the scroll. Is that how it's meant to work?

**Comment by NickMcConnell** [comment]
Yes, this is working as intended.  Mapping doesn't show terrain which behaves like dungeon floor - which outside also includes roads and grass.

**Comment by davidk64fnq** [comment]
Thanks for that
