### ISSUE TITLE
Question re monsters

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/FAangband#327]
If you don't like a particular monster in the game can you remove it in your game instance by deleting the entry in monsters.txt before starting a new game? Will that cause other issues for example if the monster is referenced elsewhere in the code?

Perhaps search for any references in monster_base.txt?

For example I find icky things and creeping coins non immersive in a Tolkien themed game.

**Comment by backwardsEric** [comment]
At a minimum, you'd have to check for references to the monster in the "friends" lines in monster.txt and remove them or comment them out.  You'd also need to remove or comment out references to that monster in "monster:" lines in the preferences files in lib/tiles, lib/customize (no monster lines there currently in FAangband), and in the preference files in your own user directory (~/.angband/FAangband when not using the Windows or Mac front end, Documents/FAangband in your home directory with the Mac front end, and lib/user with the Windows front end).

**Comment by davidk64fnq** [comment]
Thanks!
