### ISSUE TITLE
"C" versus character window info - possible bug?

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/FAangband#329]
[Linuir.zip](https://github.com/NickMcConnell/FAangband/files/7776444/Linuir.zip)

"C" shows SP 0/0

but character window shows SP 2/2

**Comment by NickMcConnell** [comment]
Nothing shows any SP for me.  What version are you playing?

**Comment by davidk64fnq** [comment]
Went back to double check and term-7 window now showing 0/0 but I'm sure it was showing 2/2 when I logged this! Will reopen if it surfaces again - thanks. Currently using FAangband-2.0.1-135-g1a84f4d41 but not sure if I was when logged this.
