### ISSUE TITLE
Bug: Another Earthquake and/or Destruction(?) Crash

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FAangband#331]
Made for Eriloth on the webserver.

Eriloth use-IDed a staff, which they're fairly certain was either Destruction or Earthquakes ("the ceiling caves in"), and it caused the game to crash.

I managed to catch the error message it invoked, as well as a small part of the map; the visible part of the error message is "faangband: obj-ignore.c:618: ignore_known_item_ok: Assertion `base_obj' failed." From what I can see of the map, they were just outside a vault, which they confirmed.

**Comment by ThatGitMITZE** [comment]
Another webserver crash, though this time without a vaguely-helpful error message, so not sure if it's the same thing; a player use-IDed a Staff of Destruction inside a vault, and like the opening issue it caused the game to crash immediately and thereafter crash on save load.

**Comment by NickMcConnell** [comment]
This is looking like object corruption issues.
