### ISSUE TITLE
Bug: Flickering Shop Entrances

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FAangband#336]
At least some shop entrances (the entrance tile itself) seem to flicker between being lit and unlit; just experienced it with the [9] in a small town. Oddly enough whether it was lit or unlit changed dependent on which tile I was on, even when both tiles were next to the tile itself.

EDIT: Playing current nightly, Windows.

**Comment by backwardsEric** [comment]
https://github.com/NickMcConnell/FAangband/pull/354 will fix this if the flickering was only present for the Travelling Merchant and the flickering was between '9' and a black space where the black space would appear if a monster was beyond the entrance and on the continuation of the line of sight from the player to the entrance (which would require that the entrance was on the corner of a building).  See https://github.com/angband/angband/issues/5098 for the similar bug report that was resolved by adding the LOS flag to the shop entrances.
