### ISSUE TITLE
Quiver Term 2 vs 6 discrepancy re display?

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/FAangband#369]
![image](https://github.com/NickMcConnell/FAangband/assets/63939880/d8211178-0e90-47ed-bc91-a6504c652027)

Is this right? Also "C" shows 40/14.

**Comment by NickMcConnell** [comment]
Yes, this is correct.  The equipment display (term 6) shows the quiver slots properly with what they contain and the labels needed to access them (0 and 1). The inventory display (term 2) only shows the effect of the quiver on the inventory - an inventory slot is taken up by every 40 missiles, so with a total of 54 it is taking up two slots (v and w).

**Comment by davidk64fnq** [comment]
Thanks!
