### ISSUE TITLE
Level feelings in Nan Dungortheb

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/FAangband#403]
Feeling squares needing to be floors means a treasure feeling in Nan Dungortheb basically never happens

**Comment by ThatGitMITZE** [comment]
This also affects forest maps in general, although it's merely annoying there instead of potentially non-existent.

**Comment by backwardsEric** [comment]
From place_feeling() in FAangband() (and Vanilla) the requirement for feeling squares is that they be passable.  That means they could end up in empty space (causing problems with Nan Dungortheb) or lava.  Change the test in Vanilla to be square_ispassable() and !square_isdamaging() (possibly with its own predicate function) and augment that test in FAangband with the additional requirement that the square is !square_isfall()?

**Comment by NickMcConnell** [comment]
OK, I had not checked and was assuming feeling squares were forced to be floors.  In fact they're not - feeling squares can be trees, and the reason feelings don't appear in play is that the player is unlikely to see enough of the trees.  So on the whole I think it's actually working as designed.  The change in https://github.com/angband/angband/pull/5831 is still a good idea, though.
