### ISSUE TITLE
Saving and reloading loses hitpoints

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/FAangband#406]
In town for a high level character

**Comment by backwardsEric** [comment]
Does the character have Athletics?  I did not locate if PU_BONUS is or'ed into player->upkeep->update after restoring from a save file, but if it is not and there's a request to update the hit points before any update to the bonuses, then the specialty flags would not have been merged into pflags and that would affect the hit point calculation.

**Comment by NickMcConnell** [comment]
Yes, it did - nice find
