### ISSUE TITLE
RFE: Roguelike Command List

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FAangband#414]
The command list in the help menu only shows the standard keyset commands; anyone using roguelike has to check outside-the-game references to look up commands.

**Comment by backwardsEric** [comment]
I'm not able to reproduce this with the current master built with the --with-no-install option.  With the option for the original keyset on, '?' displays index.txt and pressing 'a' for available commands displays command.txt.  With the option for the roguelike keyset on, '?' displays r_index.txt and pressing 'a' for available commands displays r_comm.txt.  command.txt and r_comm.txt are different, and at least from a superficial inspection, r_comm.txt does describe the commands for the roguelike keyset.

Where are you seeing this and how was FAangband built and installed?

**Comment by NickMcConnell** [comment]
Yep, I think it's MITZE just making stuff up again 😁

**Comment by ThatGitMITZE** [comment]
What it was (I think) was me reporting a problem that someone was having with not-nightly from mild inattentiveness (v2.0.1 being before the command list was made dynamic? I don't use roguelike keyset, but the problem haver was using it, I think v2.0.1 was what they were playing, and they said the command list was lying to them) and then when I checked the command list myself under nightly, I didn't bother switching to roguelike keyset because I (reasonably, I think) assumed that it would just show me the same help file regardless (as that's what every other variant I play does).
