### ISSUE TITLE
randarts appear to be lost when leaving level

### ISSUE THREAD

**Issue by chryana** [NickMcConnell/FAangband#435]
I am playing a compile of the code of late October, on Windows.
Faangband creates a set of randarts and also has a set of standarts; I noticed while playing that the artifact memory is filled with randarts that I never saw. I am unable to upload my savefile to Github for some reason, but I clearly remember finding a single randart in the list; I suspect all the other randarts were lost when I left the level they were generated on even though the option to lose artifacts when leaving a level has always been set to off. It doesn't seem to be a problem with the standarts as I think I had every single one of them at one point or another.

Steps to reproduce: play the game until artifacts are fairly common; several randarts will appear in the artifact memory even though the character never collected them.

Let me know if you need more information.

**Comment by backwardsEric** [comment]
Trying a quick and dirty way to see if this is reproducible with the "lose artifacts" option set to no:  roll new character, leave town on the stairs, use the debug commands to create a randart (in my case the first bow after Cubragol) while still on the stair in the wilderness, then go back to town without entering the grid with the created artifact.

After doing that and checking the knowledge menu, the menu entry for the artifact information is still grayed out so no artifacts have been touched yet.  Going back to the wilderness, the debug commands let me create the randart bow again (the debugging commands will generate the artifact again if it has been created and lost, but setting a breakpoint at cmd-wizard.c:847 and evaluating is_artifact_created(art) at that point indicates that the randart bow was not lost).  If I then enter the grid with the randart bow, go back to town without picking up the bow, and then check the knowledge menu for artifacts, in one attempt I saw entries for all the randarts not just the bow I touched.  In another attempt, I only saw the entry for created randart.  I don't know what was different between those two attempts.  If I then return to the wilderness, the debugging commands let me create the randart bow again (but in this case, evaluating is_artifact_created(art) at cmd-wizard.c:847 in the debugger returns true so the bow was lost after touching it and then leaving the level).

**Comment by chryana** [comment]
This makes sense. I do not know if the artifact memory contains all randarts, but there's a lot of them. I remember finding a single randart, and then I think I never found another one. All the gear my character wears is standarts; I didn't keep the randart I found.
