### ISSUE TITLE
Crash in town_gen

### ISSUE THREAD

**Issue by Cuboideb** [NickMcConnell/FAangband#83]
Got this in Android (reported by google) - The port contains FA commit 48718a2ed87b65d631ed0b25

flag_off			z-bitflag.c:248
square_set_feat	cave-square.c:1415
build_new_house 	gen-cave.c:?
town_gen		gen-cave.c:2828

**Comment by NickMcConnell** [comment]
I believe this is due to a problem with randart initialisation which is about to be fixed.
